name: Commit Stage - Upload Docker Image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      artifact:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      SCW_DOCKER_REGISTRY:
        required: true
      SCW_TOKEN:
        required: true
    outputs:
      image:
        description: The Name Of The Image
        value: ${{ jobs.build.steps.output.outputs.image }}

jobs:
  upload:
    name: Upload Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: dist

      - name: Build The Docker Container
        run: docker build -t ${{ secrets.SCW_DOCKER_REGISTRY }}/${{ inputs.image }}:${{ inputs.version }} .

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SCW_DOCKER_REGISTRY }}
          username: ${{ secrets.SCW_TOKEN }}
          password: ${{ secrets.SCW_TOKEN }}

      - name: Push The Docker Container
        run: docker push ${{ secrets.SCW_DOCKER_REGISTRY }}/${{ inputs.image }}:${{ inputs.version }}
