name: Commit Stage - Check Code With ESLint

on: workflow_call

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Packages
        run: npm ci --force

      - name: Run Lint
        run: npm run lint
