name: Deployment Stage

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SCW_ACCESS_KEY:
        required: true
      SCW_PROJECT_ID:
        required: true
      SCW_SECRET_KEY:
        required: true

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deployment-stage--terraform-apply.yml
    secrets:
      scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
      scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
      scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
