name: Deployment Stage - Deploy Frontend

on:
  workflow_call:
    secrets:
      scw_access_key:
        required: true
      scw_secret_key:
        required: true
      scw_project_id:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    env:
      TF_VAR_scw_access_key: ${{ secrets.scw_access_key }}
      TF_VAR_scw_secret_key: ${{ secrets.scw_secret_key }}
      TF_VAR_scw_project_id: ${{ secrets.scw_project_id }}
      AWS_ACCESS_KEY_ID: ${{ secrets.scw_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.scw_secret_key }}
      AWS_PROFILE: lawandorga
      TF_VAR_image_version: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.9.7

      - name: Terraform Apply
        run: |
          cd infrastructure/
          terraform init
          terraform apply --auto-approve -input=false
