name: Deployment Stage

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SCW_ACCESS_KEY:
        required: true
      SCW_PROJECT_ID:
        required: true
      SCW_SECRET_KEY:
        required: true

jobs:
  check:
    name: Check
    uses: ./.github/workflows/commit-stage--query-quality-gate-status.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy
    needs: [check]
    uses: ./.github/workflows/deployment-stage--terraform-apply.yml
    secrets:
      scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
      scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
      scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
